spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # 1. User Service (Authentication & Registration)
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**, /api/users/v3/api-docs/**

        # 2. Product Service (Main API - Protected)
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - name: AuthenticationFilter # الفلتر الأمني هنا فقط

        # 4. Order Service (Main API - Protected)
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - name: AuthenticationFilter # الفلتر الأمني هنا فقط



# إعدادات يوريكا (معدلة للعمل داخل Docker)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# إعدادات التتبع (Zipkin)
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:http://localhost:9411/api/v2/spans
