# إعدادات يوريكا (عشان لو غيرنا مكان السيرفر)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# إعدادات الـ Circuit Breaker (عشان نتحكم في قوة الفيوز من بعيد)
resilience4j.circuitbreaker.instances.product.sliding-window-size=5
resilience4j.circuitbreaker.instances.product.failure-rate-threshold=50

# رسالة ترحيب مخصصة
custom.welcome.message=Welcome to Order Service - Managed by Config Server!
